// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFkrWGha3qZV14RWQpOsPMQYB38BUMlQQ',
    appId: '1:4692045271:web:12b218f536e1259895af92',
    messagingSenderId: '4692045271',
    projectId: 'nabha-healthcare-c5c80',
    authDomain: 'nabha-healthcare-c5c80.firebaseapp.com',
    storageBucket: 'nabha-healthcare-c5c80.firebasestorage.app',
    measurementId: 'G-HBYB74GR0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkrWGha3qZV14RWQpOsPMQYB38BUMlQQ',
    appId: '1:4692045271:android:12b218f536e1259895af92',
    messagingSenderId: '4692045271',
    projectId: 'nabha-healthcare-c5c80',
    storageBucket: 'nabha-healthcare-c5c80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFkrWGha3qZV14RWQpOsPMQYB38BUMlQQ',
    appId: '1:4692045271:ios:12b218f536e1259895af92',
    messagingSenderId: '4692045271',
    projectId: 'nabha-healthcare-c5c80',
    storageBucket: 'nabha-healthcare-c5c80.firebasestorage.app',
    iosClientId:
        '4692045271-3q2j0q0j0q0j0q0j0q0j0q0j0q0j0q0j.apps.googleusercontent.com',
    iosBundleId: 'com.nabhahealth.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFkrWGha3qZV14RWQpOsPMQYB38BUMlQQ',
    appId: '1:4692045271:macos:12b218f536e1259895af92',
    messagingSenderId: '4692045271',
    projectId: 'nabha-healthcare-c5c80',
    storageBucket: 'nabha-healthcare-c5c80.firebasestorage.app',
    iosBundleId: 'com.nabhahealth.healthcare',
  );
}
